default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.280
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        exclude: ^alembic/
        stages: [pre-commit]

  - repo: https://github.com/ambv/black
    rev: "23.3.0"
    hooks:
      - id: black
        exclude: ^alembic/
        stages: [pre-commit]
#  - repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        entry: pytest
#        language: system
#        pass_filenames: false
#        always_run: true
#        stages: [pre-push]
