[tool.ruff]
select = ["A", "E", "F", "W", "I", "N"]
extend-exclude = [
  "__pycache__",
]
ignore = []
line-length = 120
src = ["src", "test"]
target-version = "py310"

[tool.ruff.per-file-ignores]
"*/__init__.py" = ["F401", "F403"]

[tool.pytest.ini_options]
pythonpath = ["src", "test"]

[tool.pytest.collect]
test_paths = ["test"]

[tool.black]
line-length = 120
skip-string-normalization = false