[tool.ruff]
# select = ["", "E", "F", "W", "I", "N"]
# ignore = []
select = [
    # "D", # pydocstyle
    # "E", # pycodestyle errors
    # "W", # pycodestyle warnings
    # "F", # pyflakes
    # "I", # isort
    # "C", # flake8-comprehensions
    # "B", # flake8-bugbear
    # "N", # pep8-naming
    # "S", # flake8-bandit
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
    "S311", # allow use random
]
extend-exclude = ["__pycache__"]
line-length = 88
target-version = "py310"

[tool.ruff.per-file-ignores]
"*/__init__.py" = ["F401", "F403"]

# [tool.ruff.pydocstyle]
# convention = "pep257" # Docstring Convention

[tool.ruff.mccabe]
max-complexity = 10 # Unlike Flake8, default to a complexity level of 10.

[tool.pytest.ini_options]
pythonpath = ["src", "test"]

[tool.pytest.collect]
test_paths = ["test"]

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py310']
